name: Deploy gh-pages
on: [push, pull_request]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    # If message contains publish
    if: contains(github.event.head_commit.message, 'deploy gh-pages')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js 18 LTS
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Gulp
        run: npm install -g gulp-cli

      - name: Install other dependencies
        run: npm install -f

      - name: Run tests
        run: gulp ci-test

      - name: Run build
        run: gulp web
